# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Ant CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Checkout Tags
        run: git fetch --tags origin
      - name: Build with Ant
        run: ant -noinput -Dbuild.number=$GITHUB_RUN_NUMBER default
      - name: Publish Artifacts
        uses: actions/upload-artifact@v3.1.0
        with:
          name: ${{ github.event.repository.name }}
          path: |
             target/generated
             !target/generated/info.json
